extends Node

# Individual game data
var timeAlive = ""
var phasesSurvived = -1
var totalNumberPhases = -1

# Player
const PLAYER_MOVEMENT_SPEED = 300
const PLAYER_STARTING_HP = 100
const PLAYER_TAKE_DAMAGE_COOLDOWN = 0.5

# Bullets
const BULLET_DESPAWN = 15
const BULLET_SPEED = 200
const BULLET_DAMAGE = 10

# Phases
const PHASE_1_ORB_SPEED = 75
const PHASE_2_ARM_SPEED = 50
const PHASE_3_ORB_SPEED = 75
const PHASE_3_ROTATION_SPEED = 0.7
const PHASE_4_ARM_SPEED = 75
const PHASE_4_ROTATION_SPEED = 0.7
const PHASE_5_ORB_SHOT_FREQUENCY = 0.5
const PHASE_5_ORB_SPEED = 75
const PHASE_6_ARM_SPEED_LINEAR = 75
const PHASE_6_ARM_SPEED_ANGULAR = 0.7
const PHASE_7_ORB_SPEED = 75
const PHASE_7_ARM_SPEED = 30
const PHASE_8_ORB_SPEED_LINEAR = 75
const PHASE_8_ORB_SPEED_ANGULAR = 0.7
const PHASE_8_ARM_SPEED = 75
const PHASE_8_ARM_SPEED_2 = 25
const PHASE_9_ORB_SPEED_LINEAR = 75
const PHASE_9_ORB_SPEED_ANGULAR = 0.7
const PHASE_10_ARM_SPEED = 50
const PHASE_11_ORB_SPEED = 75
const PHASE_12_ORB_SPEED = 75
const PHASE_13_ORB_SPEED_LINEAR = 75
const PHASE_13_ORB_SPEED_ROTATIONAL = 0.7
const PHASE_14_ORB_SPEED_LINEAR = 75
const PHASE_14_ORB_SPEED_ROTATIONAL = 0.4
const PHASE_15_ARM_SPEED_LINEAR = 75
const PHASE_15_ARM_SPEED_ROTATIONAL = 0.5
const PHASE_15_ORB_SPEED = 75
